robot_description_publisher:
  ros__parameters:
    model_path: "models/smarty"
    robot_description_topic: "/robot_description"

car_control_bridge:
  ros__parameters:
    steering_topic: "/control/steering_angle/target"
    velocity_topic: "/control/velocity/target"
    car_control_topic: "/smarty/cmd_vel"
    publish_frequency: 200

world_spawner:
  ros__parameters:
    road: "models/roads/default_road"
